// hydroflow/preset-selector.jsx
// PresetSelector — based on AutomationForms/PresetSelector.vue
// Filters presets by waterForm.systemType and tanksCount; emits onApply / onClear.

const SYSTEM_MAP = {
  drip: ['drip_tape','drip_emitter'],
  substrate_trays: ['dwc','ebb_flow','aeroponics'],
  nft: ['nft'],
};

const PRESETS = [
  { id:1, scope:'system', name:'NFT · Salad Mix · Balanced',
    irrigation_system_type:'nft', tanks_count:2, correction_profile:'balanced',
    description:'Базовый NFT-профиль для зелени. Полив каждые 15 минут, мягкая коррекция.',
    config:{ irrigation:{ interval_sec:900, duration_sec:60, correction_during_irrigation:false, decision_strategy:'task' },
             startup:{ clean_fill:600, solution_fill:600, recirculation:300 },
             correction:{ max_ec_attempts:5, max_ph_attempts:5, stabilization_sec:45 } } },
  { id:2, scope:'system', name:'NFT · Tomato · Aggressive',
    irrigation_system_type:'nft', tanks_count:2, correction_profile:'aggressive',
    description:'Для томатов на NFT. Полив каждые 10 минут, активная коррекция при поливе.',
    config:{ irrigation:{ interval_sec:600, duration_sec:90, correction_during_irrigation:true, decision_strategy:'task' },
             startup:{ clean_fill:600, solution_fill:600, recirculation:300 },
             correction:{ max_ec_attempts:8, max_ph_attempts:8, stabilization_sec:30 } } },
  { id:3, scope:'system', name:'DWC · Lettuce · Safe',
    irrigation_system_type:'dwc', tanks_count:2, correction_profile:'safe',
    description:'DWC для салата. Минимум вмешательства, длинные интервалы.',
    config:{ irrigation:{ interval_sec:1800, duration_sec:120, correction_during_irrigation:false, decision_strategy:'task' },
             startup:{ clean_fill:900, solution_fill:900, recirculation:300 },
             correction:{ max_ec_attempts:3, max_ph_attempts:3, stabilization_sec:60 } } },
  { id:4, scope:'system', name:'Drip · Strawberry · Balanced',
    irrigation_system_type:'drip_tape', tanks_count:2, correction_profile:'balanced',
    description:'Капельный полив для клубники.',
    config:{ irrigation:{ interval_sec:1800, duration_sec:120, correction_during_irrigation:false, decision_strategy:'smart_soil_v1' },
             startup:{ clean_fill:600, solution_fill:600, recirculation:300 },
             correction:{ max_ec_attempts:5, max_ph_attempts:5, stabilization_sec:45 } } },
  { id:5, scope:'system', name:'Ebb & Flow · Universal · Test',
    irrigation_system_type:'ebb_flow', tanks_count:2, correction_profile:'test',
    description:'Тестовый профиль для отладки систем приливов.',
    config:{ irrigation:{ interval_sec:1200, duration_sec:180, correction_during_irrigation:false, decision_strategy:'task' },
             startup:{ clean_fill:600, solution_fill:600, recirculation:300 },
             correction:{ max_ec_attempts:5, max_ph_attempts:5, stabilization_sec:45 } } },
  { id:101, scope:'custom', name:'Мой Tomato r3 · копия',
    irrigation_system_type:'nft', tanks_count:2, correction_profile:'balanced',
    description:'Сохранённый из Zone-A 2026-02-14.',
    config:{ irrigation:{ interval_sec:600, duration_sec:120, correction_during_irrigation:true, decision_strategy:'task' },
             startup:{ clean_fill:480, solution_fill:480, recirculation:240 },
             correction:{ max_ec_attempts:6, max_ph_attempts:6, stabilization_sec:35 } } },
];

const PROFILE_LABELS = { safe:'Мягкий', balanced:'Оптимальный', aggressive:'Агрессивный', test:'Тестовый' };
const PROFILE_TONES  = { safe:'growth', balanced:'brand', aggressive:'warn', test:'neutral' };

function PresetSelector({ waterForm, onApply, onClear }){
  const compat = SYSTEM_MAP[waterForm.systemType] || [];
  const filtered = PRESETS.filter(p =>
    p.tanks_count === waterForm.tanksCount &&
    (compat.length===0 || compat.includes(p.irrigation_system_type))
  );
  const system = filtered.filter(p=>p.scope==='system');
  const custom = filtered.filter(p=>p.scope==='custom');
  const current = waterForm._preset;
  const isModified = current && (
    current.baseline?.intervalMinutes !== waterForm.intervalMinutes ||
    current.baseline?.durationSeconds !== waterForm.durationSeconds ||
    current.baseline?.correctionDuringIrrigation !== waterForm.correctionDuringIrrigation ||
    current.baseline?.tanksCount !== waterForm.tanksCount
  );

  const onChange = (e) => {
    const v = e.target.value;
    if (!v) return onClear();
    const p = PRESETS.find(x => x.id === Number(v));
    if (p) onApply(p);
  };

  return (
    <div style={{padding:12,border:'1px solid var(--brand)',borderRadius:6,
      background:'var(--brand-soft)',display:'flex',flexDirection:'column',gap:10}}>
      <div style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap'}}>
        <Ic.bookmark style={{color:'var(--brand)'}}/>
        <span style={{fontSize:12,fontWeight:600,color:'var(--brand-ink)'}}>Профиль автоматики (preset)</span>
        <select value={current?.id ?? ''} onChange={onChange}
          style={{padding:'6px 8px',border:'1px solid var(--line-strong)',borderRadius:4,
            background:'var(--bg-panel)',color:'var(--text)',fontSize:12,minWidth:340,
            fontFamily:'var(--mono)'}}>
          <option value="">— Настроить с нуля —</option>
          {system.length>0 && (
            <optgroup label="Системные">
              {system.map(p=>(
                <option key={p.id} value={p.id}>
                  {p.name} · {Math.round(p.config.irrigation.interval_sec/60)}мин/{p.config.irrigation.duration_sec}с
                </option>
              ))}
            </optgroup>
          )}
          {custom.length>0 && (
            <optgroup label="Мои профили">
              {custom.map(p=>(<option key={p.id} value={p.id}>{p.name}</option>))}
            </optgroup>
          )}
        </select>
        {isModified && <Chip tone="warn">изменено</Chip>}
        {filtered.length===0 && (
          <span style={{fontSize:11,color:'var(--text-muted)'}}>
            Нет совместимых: <span className="mono">{waterForm.systemType}</span> · <span className="mono">{waterForm.tanksCount} бак(ов)</span>
          </span>
        )}
      </div>

      {current ? (
        <div style={{display:'flex',flexDirection:'column',gap:6,padding:'8px 10px',
          background:'var(--bg-panel)',border:'1px solid var(--line)',borderRadius:4}}>
          <div style={{fontSize:11,color:'var(--text-muted)',lineHeight:1.5}}>
            {PRESETS.find(p=>p.id===current.id)?.description}
          </div>
          <div style={{display:'flex',gap:6,flexWrap:'wrap'}}>
            {current.correction_profile && (
              <Chip tone={PROFILE_TONES[current.correction_profile]||'neutral'}>
                {PROFILE_LABELS[current.correction_profile]||current.correction_profile}
              </Chip>
            )}
            <Chip tone="neutral"><span className="mono">{current.irrigation_system_type}</span></Chip>
            <Chip tone="neutral">{waterForm.tanksCount} бака</Chip>
            <Chip tone="neutral">
              Полив: <span className="mono">{waterForm.intervalMinutes}м/{waterForm.durationSeconds}с</span>
            </Chip>
            <Chip tone="neutral">
              Корр. при поливе: {waterForm.correctionDuringIrrigation?'да':'нет'}
            </Chip>
          </div>
        </div>
      ) : (
        <div style={{fontSize:11,color:'var(--text-muted)'}}>
          Ручная настройка — заполните параметры вручную ниже.
        </div>
      )}
    </div>
  );
}

Object.assign(window, { PresetSelector });

// backend/laravel/resources/js/Components/AutomationForms/PresetSelector.vue
<template>
  <div class="p-3 border border-brand bg-brand-soft rounded-md flex flex-col gap-2.5">
    <div class="flex items-center gap-2.5 flex-wrap">
      <Ic
        name="bookmark"
        class="text-brand shrink-0"
      />
      <span class="text-xs font-semibold text-brand-ink">Профиль автоматики</span>
      <Chip
        v-if="selectedPreset && isModified"
        tone="warn"
      >
        изменено
      </Chip>
    </div>

    <div class="flex items-center gap-2 flex-wrap">
      <select
        v-if="!loading"
        class="block min-w-[300px] flex-1 h-8 rounded-md border border-[var(--border-muted)] bg-[var(--bg-surface)] text-[var(--text-primary)] px-2.5 text-sm font-mono outline-none focus-visible:ring-2 focus-visible:ring-brand"
        :value="selectedPreset?.id ?? ''"
        :disabled="!canConfigure"
        @change="onSelectChange"
      >
        <option value="">
          — Настроить с нуля —
        </option>
        <optgroup
          v-if="systemPresets.length > 0"
          label="Системные"
        >
          <option
            v-for="preset in systemPresets"
            :key="preset.id"
            :value="preset.id"
          >
            {{ preset.name }} · {{ correctionProfileLabel(preset.correction_profile) }} · {{ Math.round(preset.config.irrigation.interval_sec / 60) }}мин
          </option>
        </optgroup>
        <optgroup
          v-if="customPresets.length > 0"
          label="Мои профили"
        >
          <option
            v-for="preset in customPresets"
            :key="preset.id"
            :value="preset.id"
          >
            {{ preset.name }}
          </option>
        </optgroup>
      </select>
      <div
        v-else
        class="flex items-center gap-2 text-xs text-[var(--text-muted)]"
      >
        <span class="inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-brand border-t-transparent"></span>
        Загрузка профилей...
      </div>
    </div>

    <div
      v-if="selectedPreset"
      class="flex flex-col gap-2 px-2.5 py-2 bg-[var(--bg-surface)] border border-[var(--border-muted)] rounded-sm"
    >
      <p
        v-if="selectedPreset.description"
        class="text-[11px] leading-relaxed text-[var(--text-muted)] whitespace-pre-line"
      >
        {{ selectedPreset.description }}
      </p>

      <div class="flex flex-wrap gap-1.5">
        <Chip
          v-if="selectedPreset.correction_profile"
          :tone="correctionProfileTone(selectedPreset.correction_profile)"
        >
          {{ correctionProfileLabel(selectedPreset.correction_profile) }}
        </Chip>
        <Chip tone="neutral">
          <span class="font-mono">{{ selectedPreset.irrigation_system_type }}</span>
        </Chip>
        <Chip tone="neutral">
          {{ selectedPreset.tanks_count }} бака
        </Chip>
        <Chip tone="neutral">
          Полив:
          <span class="font-mono ml-1">
            {{ Math.round(selectedPreset.config.irrigation.interval_sec / 60) }}м/{{ selectedPreset.config.irrigation.duration_sec }}с
          </span>
        </Chip>
        <Chip tone="neutral">
          Корр. при поливе: {{ selectedPreset.config.irrigation.correction_during_irrigation ? 'да' : 'нет' }}
        </Chip>
      </div>
    </div>

    <p
      v-else-if="!loading"
      class="text-[11px] text-[var(--text-dim)]"
    >
      Ручная настройка — заполните параметры ниже вручную.
    </p>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { Chip } from '@/Components/Shared/Primitives'
import type { ChipTone } from '@/Components/Shared/Primitives/Chip.vue'
import Ic from '@/Components/Icons/Ic.vue'
import type { ZoneAutomationPreset } from '@/types/ZoneAutomationPreset'
import type { WaterFormState } from '@/composables/zoneAutomationTypes'
import {
  useZoneAutomationPresets,
  applyPresetToWaterForm,
  isPresetModified,
} from '@/composables/useZoneAutomationPresets'

const props = defineProps<{
  waterForm: WaterFormState
  canConfigure: boolean
  tanksCount?: number
  irrigationSystemType?: string
}>()

const emit = defineEmits<{
  presetApplied: [preset: ZoneAutomationPreset]
  presetCleared: []
  'update:waterForm': [form: WaterFormState]
}>()

const { presets, loading, loadPresets } = useZoneAutomationPresets()

const selectedPreset = ref<ZoneAutomationPreset | null>(null)

const compatibleIrrigationTypes = computed<string[]>(() => {
  const st = props.waterForm.systemType
  const map: Record<string, string[]> = {
    drip: ['drip_tape', 'drip_emitter'],
    substrate_trays: ['dwc', 'ebb_flow', 'aeroponics'],
    nft: ['nft'],
  }
  return map[st] ?? []
})

const filteredPresets = computed(() =>
  presets.value.filter((p) => {
    if (props.tanksCount !== undefined && p.tanks_count !== props.tanksCount) return false
    if (
      compatibleIrrigationTypes.value.length > 0 &&
      !compatibleIrrigationTypes.value.includes(p.irrigation_system_type)
    )
      return false
    return true
  }),
)

const systemPresets = computed(() => filteredPresets.value.filter((p) => p.scope === 'system'))
const customPresets = computed(() => filteredPresets.value.filter((p) => p.scope === 'custom'))

const isModified = computed(() => {
  if (!selectedPreset.value) return false
  return isPresetModified(selectedPreset.value, props.waterForm)
})

function onSelectChange(event: Event) {
  const value = (event.target as HTMLSelectElement).value
  if (!value) {
    selectedPreset.value = null
    emit('presetCleared')
    return
  }
  const preset = filteredPresets.value.find((p) => p.id === Number(value))
  if (preset) {
    selectedPreset.value = preset
    const updated = applyPresetToWaterForm(preset, props.waterForm)
    emit('update:waterForm', updated)
    emit('presetApplied', preset)
  }
}

function correctionProfileLabel(profile: string | null): string {
  if (!profile) return ''
  const labels: Record<string, string> = {
    safe: 'Мягкий',
    balanced: 'Оптимальный',
    aggressive: 'Агрессивный',
    test: 'Тестовый',
  }
  return labels[profile] ?? profile
}

function correctionProfileTone(profile: string): ChipTone {
  const map: Record<string, ChipTone> = {
    safe: 'growth',
    balanced: 'brand',
    aggressive: 'warn',
    test: 'neutral',
  }
  return map[profile] ?? 'neutral'
}

onMounted(() => {
  loadPresets()
})

watch(
  () => props.tanksCount,
  () => {
    loadPresets()
  },
)

watch(
  () => props.waterForm.systemType,
  () => {
    const preset = selectedPreset.value
    if (
      preset &&
      !filteredPresets.value.some((p) => p.id === preset.id)
    ) {
      selectedPreset.value = null
      emit('presetCleared')
    }
  },
)
</script>
